source_set("navigation") {
  sources = [
    "document_cosmetic_policy.cc",
    "document_cosmetic_policy.h",
    "request_policy.cc",
    "request_policy.h",
    "url_cleaner.cc",
    "url_cleaner.h",
  ]

  deps = [
    "//fireball/browser:domain",
    "//fireball/components/adblock:adblock_policy",
    "//fireball/components/egress",
  ]
}
