// Generated by tools/url_cleaner_rules.py. Do not edit.
#ifndef FIREBALL_COMPONENTS_NAVIGATION_GENERATED_URL_CLEANER_RULES_H_
#define FIREBALL_COMPONENTS_NAVIGATION_GENERATED_URL_CLEANER_RULES_H_

#include <array>
#include <string_view>

namespace fireball::navigation::generated {

inline constexpr std::string_view kUrlCleanerRulesVersion = "2026.8.1";
inline constexpr std::string_view kUrlCleanerRulesSha256 = "240a51609a31480278d0f972136bd04fb573c64ce30ae7ec706b8008108edaf0";
inline constexpr std::array<std::string_view, 16> kUrlCleanerTrackingParameters = {{
    "_hsenc",
    "_hsmi",
    "dclid",
    "fbclid",
    "gclid",
    "igshid",
    "mc_cid",
    "mc_eid",
    "msclkid",
    "utm_campaign",
    "utm_content",
    "utm_id",
    "utm_medium",
    "utm_source",
    "utm_term",
    "vero_id",
}};

}  // namespace fireball::navigation::generated

#endif  // FIREBALL_COMPONENTS_NAVIGATION_GENERATED_URL_CLEANER_RULES_H_
