#!/usr/bin/env python3
"""Validate Fireball's default-deny background-network policy and generate C++."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any

ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_-]{2,63}$")
OWNER_PATTERN = re.compile(r"^[a-z0-9][a-z0-9_.-]{2,127}$")
PHASES = {"startup": "kStartup", "post_startup": "kPostStartup"}


class PolicyError(ValueError):
    pass


def load_policy(path: pathlib.Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)
    if not isinstance(document, dict):
        raise PolicyError("policy root must be an object")
    return document


def validate_policy(document: dict[str, Any]) -> None:
    if set(document) != {"schema_version", "default_action", "rules"}:
        raise PolicyError("policy must contain only schema_version, default_action and rules")
    if document["schema_version"] != 1:
        raise PolicyError("unsupported policy schema")
    if document["default_action"] != "deny":
        raise PolicyError("default_action must remain deny")
    if not isinstance(document["rules"], list):
        raise PolicyError("rules must be an array")

    seen_ids: set[str] = set()
    seen_keys: set[tuple[str, str]] = set()
    expected_fields = {"id", "owner", "phase", "requires_user_consent", "purpose"}
    for index, rule in enumerate(document["rules"]):
        if not isinstance(rule, dict) or set(rule) != expected_fields:
            raise PolicyError(f"rule[{index}] has an unexpected shape")
        rule_id = rule["id"]
        if not isinstance(rule_id, str) or ID_PATTERN.fullmatch(rule_id) is None:
            raise PolicyError(f"rule[{index}].id is invalid")
        if rule_id in seen_ids:
            raise PolicyError(f"duplicate rule id: {rule_id}")
        seen_ids.add(rule_id)
        owner = rule["owner"]
        phase = rule["phase"]
        if not isinstance(owner, str) or OWNER_PATTERN.fullmatch(owner) is None:
            raise PolicyError(f"{rule_id}: invalid owner")
        if phase not in PHASES:
            raise PolicyError(f"{rule_id}: invalid phase")
        key = (owner, phase)
        if key in seen_keys:
            raise PolicyError(f"{rule_id}: duplicate owner and phase")
        seen_keys.add(key)
        if rule["requires_user_consent"] is not True:
            raise PolicyError(f"{rule_id}: background traffic must require explicit user consent")
        if not isinstance(rule["purpose"], str) or not rule["purpose"].strip():
            raise PolicyError(f"{rule_id}: purpose is required")


def generate_cpp(document: dict[str, Any]) -> str:
    validate_policy(document)
    rules = document["rules"]
    lines = [
        "// Generated by tools/network_policy.py. Do not edit.",
        f"constexpr std::array<NetworkPolicyEntry, {len(rules)}> kNetworkPolicy = {{{{",
    ]
    for rule in rules:
        consent = "true" if rule["requires_user_consent"] else "false"
        lines.append(
            f'    {{"{rule["owner"]}", NetworkPhase::{PHASES[rule["phase"]]}, {consent}}},'
        )
    lines.extend(["}};", ""])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    root = pathlib.Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("check", "generate"))
    parser.add_argument("--policy", type=pathlib.Path, default=root / "policies/startup_network.json")
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=root / "fireball/components/privacy/startup_network_policy.inc",
    )
    return parser


def main() -> int:
    arguments = build_parser().parse_args()
    try:
        generated = generate_cpp(load_policy(arguments.policy))
        if arguments.command == "generate":
            arguments.output.write_text(generated, encoding="utf-8")
        elif not arguments.output.is_file() or arguments.output.read_text(encoding="utf-8") != generated:
            raise PolicyError("generated C++ is stale; run tools/network_policy.py generate")
    except (OSError, json.JSONDecodeError, PolicyError) as error:
        print(f"fireball-network-policy: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
